### ISSUE TITLE
Object version endpoints response broken

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/ctibutler#25]
e.g.

```
curl -X 'GET' \
  'http://127.0.0.1:8006/api/v1/attack-enterprise/objects/T1499.004/versions/' \
  -H 'accept: application/json'
```

```
[
  {
    "modified": "2022-05-11T14:00:00.188Z",
    "notes": [
      "v",
      "v",
      "v",
      "v",
      "v",
      "v"
    ]
  },
  {
    "modified": "2022-03-25T18:11:13.604Z",
    "notes": [
      "v"
    ]
  },
  {
    "modified": "2021-03-29T16:09:41.559Z",
    "notes": [
      "v",
      "v",
      "v"
    ]
  },
  {
    "modified": "2020-03-29T02:07:27.508Z",
    "notes": [
      "v",
      "v",
      "v",
      "v",
      "v",
      "v"
    ]
  }
]
```

**Comment by fqrious** [comment]
please pull latest

**Comment by himynamesdave** [comment]
getting critical error


```
django-1      | IndexError: list index out of range
django-1      | [2024-10-25 - 15:49:12] ERROR - Internal Server Error: /api/v1/attack-enterprise/objects/T1499.004/versions/
django-1      | Traceback (most recent call last):
django-1      |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
django-1      |     response = get_response(request)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
django-1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
django-1      |     return view_func(request, *args, **kwargs)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
django-1      |     return self.dispatch(request, *args, **kwargs)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
django-1      |     response = self.handle_exception(exc)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
django-1      |     self.raise_uncaught_exception(exc)
django-1      |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django-1      |     raise exc
django-1      |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
django-1      |     response = handler(request, *args, **kwargs)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.11/site-packages/drf_spectacular/drainage.py", line 207, in wrapped_method
django-1      |     return method(self, request, *args, **kwargs)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/src/app/ctibutler/server/views.py", line 118, in object_versions
django-1      |     return ArangoDBHelper(f'mitre_attack_{self.matrix}_vertex_collection', request).get_mitre_modified_versions(attack_id)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/src/app/ctibutler/server/arango_helpers.py", line 491, in get_mitre_modified_versions
django-1      |     mod['notes'] = self.clean_and_sort_versions(mod['notes'], prefix=version_prefix)
django-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/src/app/ctibutler/server/arango_helpers.py", line 510, in clean_and_sort_versions
django-1      |     versions = sorted([
django-1      |                       ^
django-1      |   File "/usr/src/app/ctibutler/server/arango_helpers.py", line 511, in <listcomp>
django-1      |     v.split("=")[1].replace('_', ".")
django-1      |     ~~~~~~~~~~~~^^^
django-1      | IndexError: list index out of range


```

**Comment by fqrious** [comment]
this is not latest
